### ISSUE TITLE
Angular tests fail

### ISSUE THREAD

**Issue by maiermic** [chromaui/learnstorybook-code#48]
Some tests on the [current](2f113cdd25bf4b996a0a9d5fa4cbcd92ecf9ba60) branch [angular](https://github.com/chromaui/learnstorybook-code/tree/angular) fail. I get the following output, when I run `yarn run jest`:

```
yarn run v1.22.10
$ jest
 PASS  src/app/tasks/components/pure-task-list.component.spec.ts
 PASS  src/app/app.component.spec.ts
 FAIL  src/angularshots.test.ts
  ● Storyshots › InboxScreen › default

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "Storyshots InboxScreen default 1".

    - Snapshot
    + Received

    @@ -3,194 +3,202 @@
        data={[Function Object]}
        target={[Function ViewContainerRef_]}
      >
        <ng-component>
          <inbox-screen>
    -
    -
    -       <div
    -         class="page lists-show"
    +       <pure-inbox-screen
    +         ng-reflect-error=""
            >
    -         <nav>
    -           <h1
    -             class="title-page"
    -           >
    -             <span
    -               class="title-wrapper"
    +
    +
    +         <div
    +           class="page lists-show"
    +         >
    +           <nav>
    +             <h1
    +               class="title-page"
                  >
    -               Taskbox
    -             </span>
    -           </h1>
    -         </nav>
    -         <task-list>
    -           <pure-task-list
    -             ng-reflect-tasks="[object Object],[object Object"
    -           >
    -             <div
    -               class="list-items"
    +               <span
    +                 class="title-wrapper"
    +               >
    +                 Taskbox
    +               </span>
    +             </h1>
    +           </nav>
    +           <task-list>
    +             <pure-task-list
    +               ng-reflect-tasks="[object Object],[object Object"
                  >
    -
    -               <task-item
    -                 ng-reflect-task="[object Object]"
    +               <div
    +                 class="list-items"
                    >
    -                 <div
    -                   class="list-item TASK_INBOX"
    +
    +                 <task-item
    +                   ng-reflect-task="[object Object]"
                      >
    -                   <label
    -                     class="checkbox"
    -                   >
    -                     <input
    -                       disabled="true"
    -                       name="checked"
    -                       type="checkbox"
    -                     />
    -                     <span
    -                       class="checkbox-custom"
    -                     />
    -                   </label>
                        <div
    -                     class="title"
    +                     class="list-item TASK_INBOX"
    +                     id="1"
                        >
    -                     <input
    -                       placeholder="Input title"
    -                       readonly="true"
    -                       type="text"
    -                     />
    -                   </div>
    -                   <div
    -                     class="actions"
    -                   >
    -
    -                     <a>
    +                     <label
    +                       class="checkbox"
    +                     >
    +                       <input
    +                         disabled="true"
    +                         name="checked"
    +                         type="checkbox"
    +                       />
                            <span
    -                         class="icon-star"
    +                         class="checkbox-custom"
                            />
    -                     </a>
    +                     </label>
    +                     <div
    +                       class="title"
    +                     >
    +                       <input
    +                         placeholder="Input title"
    +                         readonly="true"
    +                         type="text"
    +                       />
    +                     </div>
    +                     <div
    +                       class="actions"
    +                     >
    +
    +                       <a>
    +                         <span
    +                           class="icon-star"
    +                         />
    +                       </a>
    +                     </div>
                        </div>
    -                 </div>
    -               </task-item>
    -               <task-item
    -                 ng-reflect-task="[object Object]"
    -               >
    -                 <div
    -                   class="list-item TASK_INBOX"
    +                 </task-item>
    +                 <task-item
    +                   ng-reflect-task="[object Object]"
                      >
    -                   <label
    -                     class="checkbox"
    -                   >
    -                     <input
    -                       disabled="true"
    -                       name="checked"
    -                       type="checkbox"
    -                     />
    -                     <span
    -                       class="checkbox-custom"
    -                     />
    -                   </label>
                        <div
    -                     class="title"
    +                     class="list-item TASK_INBOX"
    +                     id="2"
                        >
    -                     <input
    -                       placeholder="Input title"
    -                       readonly="true"
    -                       type="text"
    -                     />
    -                   </div>
    -                   <div
    -                     class="actions"
    -                   >
    -
    -                     <a>
    +                     <label
    +                       class="checkbox"
    +                     >
    +                       <input
    +                         disabled="true"
    +                         name="checked"
    +                         type="checkbox"
    +                       />
                            <span
    -                         class="icon-star"
    +                         class="checkbox-custom"
                            />
    -                     </a>
    +                     </label>
    +                     <div
    +                       class="title"
    +                     >
    +                       <input
    +                         placeholder="Input title"
    +                         readonly="true"
    +                         type="text"
    +                       />
    +                     </div>
    +                     <div
    +                       class="actions"
    +                     >
    +
    +                       <a>
    +                         <span
    +                           class="icon-star"
    +                         />
    +                       </a>
    +                     </div>
                        </div>
    -                 </div>
    -               </task-item>
    -               <task-item
    -                 ng-reflect-task="[object Object]"
    -               >
    -                 <div
    -                   class="list-item TASK_INBOX"
    +                 </task-item>
    +                 <task-item
    +                   ng-reflect-task="[object Object]"
                      >
    -                   <label
    -                     class="checkbox"
    -                   >
    -                     <input
    -                       disabled="true"
    -                       name="checked"
    -                       type="checkbox"
    -                     />
    -                     <span
    -                       class="checkbox-custom"
    -                     />
    -                   </label>
                        <div
    -                     class="title"
    +                     class="list-item TASK_INBOX"
    +                     id="3"
                        >
    -                     <input
    -                       placeholder="Input title"
    -                       readonly="true"
    -                       type="text"
    -                     />
    -                   </div>
    -                   <div
    -                     class="actions"
    -                   >
    -
    -                     <a>
    +                     <label
    +                       class="checkbox"
    +                     >
    +                       <input
    +                         disabled="true"
    +                         name="checked"
    +                         type="checkbox"
    +                       />
                            <span
    -                         class="icon-star"
    +                         class="checkbox-custom"
                            />
    -                     </a>
    +                     </label>
    +                     <div
    +                       class="title"
    +                     >
    +                       <input
    +                         placeholder="Input title"
    +                         readonly="true"
    +                         type="text"
    +                       />
    +                     </div>
    +                     <div
    +                       class="actions"
    +                     >
    +
    +                       <a>
    +                         <span
    +                           class="icon-star"
    +                         />
    +                       </a>
    +                     </div>
                        </div>
    -                 </div>
    -               </task-item>
    -               <task-item
    -                 ng-reflect-task="[object Object]"
    -               >
    -                 <div
    -                   class="list-item TASK_INBOX"
    +                 </task-item>
    +                 <task-item
    +                   ng-reflect-task="[object Object]"
                      >
    -                   <label
    -                     class="checkbox"
    -                   >
    -                     <input
    -                       disabled="true"
    -                       name="checked"
    -                       type="checkbox"
    -                     />
    -                     <span
    -                       class="checkbox-custom"
    -                     />
    -                   </label>
                        <div
    -                     class="title"
    +                     class="list-item TASK_INBOX"
    +                     id="4"
                        >
    -                     <input
    -                       placeholder="Input title"
    -                       readonly="true"
    -                       type="text"
    -                     />
    -                   </div>
    -                   <div
    -                     class="actions"
    -                   >
    -
    -                     <a>
    +                     <label
    +                       class="checkbox"
    +                     >
    +                       <input
    +                         disabled="true"
    +                         name="checked"
    +                         type="checkbox"
    +                       />
                            <span
    -                         class="icon-star"
    +                         class="checkbox-custom"
                            />
    -                     </a>
    +                     </label>
    +                     <div
    +                       class="title"
    +                     >
    +                       <input
    +                         placeholder="Input title"
    +                         readonly="true"
    +                         type="text"
    +                       />
    +                     </div>
    +                     <div
    +                       class="actions"
    +                     >
    +
    +                       <a>
    +                         <span
    +                           class="icon-star"
    +                         />
    +                       </a>
    +                     </div>
                        </div>
    -                 </div>
    -               </task-item>
    -
    -
    -             </div>
    -           </pure-task-list>
    -         </task-list>
    -       </div>
    +                 </task-item>
    +
    +
    +               </div>
    +             </pure-task-list>
    +           </task-list>
    +         </div>
    +       </pure-inbox-screen>
          </inbox-screen>
        </ng-component>
      </storybook-dynamic-app-root>

      at match (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:25:22)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at node_modules/zone.js/dist/zone.js:872:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:159:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:420:36)
      at Zone.Object.<anonymous>.Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
      at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)

  ● Storyshots › InboxScreen › error

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "Storyshots InboxScreen error 1".

    - Snapshot
    + Received

    @@ -2,11 +2,13 @@
        cfr={[Function CodegenComponentFactoryResolver]}
        data={[Function Object]}
        target={[Function ViewContainerRef_]}
      >
        <ng-component>
    -     <inbox-screen>
    +     <pure-inbox-screen
    +       ng-reflect-error="Something!"
    +     >

            <div
              class="page lists-show"
            >
              <div
    @@ -26,8 +28,8 @@
                  Something went wrong
                </div>
              </div>
            </div>

    -     </inbox-screen>
    +     </pure-inbox-screen>
        </ng-component>
      </storybook-dynamic-app-root>

      at match (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:25:22)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at node_modules/zone.js/dist/zone.js:872:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:159:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:420:36)
      at Zone.Object.<anonymous>.Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
      at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       2 failed, 10 passed, 12 total
Snapshots:   0 total
Time:        4.227s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jonniebigodes** [comment]
Closing this issue as the angular branch received some updates and is now up to par with the latest Storybook version
